package com.ash.resonance.common;

import java.security.SecureRandom;
import java.util.UUID;

/**
 * Generates time-ordered UUIDv7 values (draft RFC 9562) on the JVM side.
 *
 * Mirrors the Postgres uuid_generate_v7() function in V1__init.sql — both
 * produce the same layout, so IDs generated here sort the same way as ones
 * generated by a DB default, and a client (once we support client-generated
 * IDs for offline-created rows) can mint its own collision-safe ID with the
 * same scheme.
 */
public final class UuidV7 {

    private static final SecureRandom RANDOM = new SecureRandom();

    private UuidV7() {
    }

    public static UUID generate() {
        long timestampMs = System.currentTimeMillis();
        byte[] randomBytes = new byte[10];
        RANDOM.nextBytes(randomBytes);

        long mostSigBits = (timestampMs & 0xFFFFFFFFFFFFL) << 16;
        mostSigBits |= 0x7000L; // version 7
        mostSigBits |= (randomBytes[0] & 0x0FL) << 8;
        mostSigBits |= (randomBytes[1] & 0xFFL);

        long leastSigBits = 0x8000000000000000L; // variant 10xx
        leastSigBits |= (long) (randomBytes[2] & 0x3F) << 56;
        for (int i = 3; i < 10; i++) {
            leastSigBits |= (long) (randomBytes[i] & 0xFF) << (8 * (9 - i));
        }

        return new UUID(mostSigBits, leastSigBits);
    }
}
